### PR TITLE
feat(auth): initial with auth features

### PR DESCRIPTION
**Pull request by r17x**

### CODE REVIEW

**Comment by nevindra** [comment]
lgtm

**Comment by r17x** [comment]
@nevindra next, merge with `squash` biar 1 konteks per PR

**Comment by nevindra** [comment]
> @nevindra next, merge with `squash` biar 1 konteks per PR

oke, thanks infonya

**Comment by nevindra** [comment]
@r17x gue baru sadar lu bikinnya DEVELOPMENT.md ya, jd ga langsung ke readme. mau dimerge aja next commit?

**Comment by r17x** [comment]
@nevindra 

Pasti, update di README, nanti di link kesana.

**Pull request merged**
